language: node_js
node_js:
- '5'
  - /^v[0-9]/
addons:
  code_climate:
    repo_token: 2f63066f180f268aae0b901921cfe569492edf1cd4376f0f0c60c43d655b4786
before_deploy:
- npm run build
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- npm run coverage
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: oQn09I0cyPyd+1OqgJxLYip5GYunIwmE8X+Bsl18RvtjQkpoh4tJLk7WvOp70v0kFmWBFgnGQcIXNyBO5P01lrCYnmRkdu8HvgBHZcXQ9KRhZtQ9mRuev9ZTgtwKkiGm9UORZPb2VF8tJfrUkXEdnVUl8xiEMmCknZaTYGws019/x9NFWbIGe7p4tom8ZeWb5cWgUBDa+JxxEYvx19mn1zedODfUh7FwtGTzbOZ2x0VtznOFhpmpus3u7lQCHF41hZwShsvR2lRI93W2FY6rTMpm+nhxMDDBLUfvxIWxvk3L7HRD8iFNASBSGQu4mbwnlYxTJi162+rQ/QkpAhIwdooTzskxtyFAzLcUxZtQF5QBiM5dPm64/ZzemSuKYpJgrEeLsnRIcAVF8hEpCMP4KQx3H6rm0JTq3vQnwKkW10AACb2hzg74dW73acJz9pQHfyeY6sno5zhKQvlluRGh6ScebTUvVawh3BXuCml6CAVRH4u7gDR+9OAfn/+w0no0VC8qccEJEXJ20auj3hXS+KPF8ORDRgVG0dsIOaLkmD+GqXzDB8g+wvypzZOlpQWgSKt/HGgacs0Rbm2f5GyB+UBqTQw7kVXlCJIsS3bHz7u0o1Xg4djP6R+bN7s7FzvnikXwNyxXXH4JaAtYecgdJuWX0FB4QPLAsEdbylhtObQ=
  on:
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
